// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface DataSocialLinkStoryblok {
  url?: string;
  icon?: number | string;
  component: "dataSocialLink";
  _uid: string;
  [k: string]: any;
}

export interface MetaGlobalOptionsStoryblok {
  email?: string;
  telDerby?: string;
  telLeicester?: string;
  telWarwick?: string;
  socialLinks?: (ISbStoryData<DataSocialLinkStoryblok> | string)[];
  component: "metaGlobalOptions";
  _uid: string;
  [k: string]: any;
}

export interface TemplateNewsStoryblok {
  component: "templateNews";
  _uid: string;
  [k: string]: any;
}

export interface TemplatePageStoryblok {
  component: "templatePage";
  _uid: string;
  [k: string]: any;
}
