name: Update CHANGELOG

on:
  release:
    types:
      - released

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    name: Changelog
    uses: effect-digital/organisation/.github/workflows/update-changelog.yml@main
    secrets:
      PAT: ${{ secrets.PAT_EFFECTDEV }}
